json.id home.id
json.user_id home.user_id
json.name home.name
json.guestbook_comments home.guestbook_comments
json.is_active home.is_active 
json.wifi_password home.wifi_password 
json.bedrooms home.bedrooms 
json.bathrooms home.bathrooms 
json.zipcode home.zipcode 
json.state home.state 
json.created_at home.created_at 
json.updated_at home.updated_at 